// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzmzhudmsjeocczyuikb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bXpodWRtc2plb2Njenl1aWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTEwOTIsImV4cCI6MjA2MDQ4NzA5Mn0.tmEFmo5VewpRPPtvfBgOvOTT2RfXlR5Ani5VQ82alv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);